version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7
        environment:
          PIPENV_VENV_IN_PROJECT: true
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-pipenv-{{ checksum "Pipfile.lock" }}
            - v2-pipenv-
      - run:
          name: install dependencies
          command: |
            sudo pip install pipenv
            pipenv install --dev
      - run:
          name: setup pokedex
          command: pipenv run pokedex lookup eevee 2>/dev/null || pipenv run pokedex setup
      - save_cache:
          paths:
            - .venv
          key: v2-pipenv-{{ checksum "Pipfile.lock" }}
      - run:
          name: run tests
          command: pipenv run pytest --cov=./
      - run:
          name: upload coverage
          command: pipenv run bash <(curl -s https://codecov.io/bash)
